// templates/min/web3js-react-dapp-min/src/App.tsx
import { useState } from "react";

import Web3Service from "./web3/web3-service";

function App() {
  const hasProvider = Web3Service.provider !== undefined;
  const [chainId, setChainId] = useState<bigint>(0n);
  if (hasProvider) {
    Web3Service.web3.eth.getChainId().then(setChainId);
  }

  return (
    <main>
      <h1>Web3.js + React Minimal dApp Template</h1>
      <div>
        This is a sample project that demonstrates using{" "}
        <a href="https://web3js.org/">Web3.js</a> with the{" "}
        <a href="https://react.dev/">React</a> front-end framework.
        <ul>
          <li>
            <a href="https://docs.web3js.org/">Web3.js Docs</a>
          </li>
          <li>
            <a href="https://react.dev/learn">React Docs</a>
          </li>
        </ul>
        Learn more about this project and its design by referring to the{" "}
        <a href="https://github.com/web3/create-web3js-dapp/blob/main/templates/min/web3js-react-dapp-min/README.md">
          GitHub README
        </a>
        .
      </div>
      {!hasProvider ? (
        <>
          <h2>Install a Wallet</h2>
          <div>Install a wallet browser extension:</div>
          <ul>
            <li>
              <a href="https://www.enkrypt.com/download.html">Enkrypt</a>
            </li>
            <li>
              <a href="https://www.exodus.com/download/">Exodus</a>
            </li>
            <li>
              <a href="https://metamask.io/download/">MetaMask</a>
            </li>
            <li>
              <a href="https://trustwallet.com/download">Trust Wallet</a>
            </li>
          </ul>
        </>
      ) : (
        <>
          <h2>Network Details</h2>
          <div>Chain ID: {chainId.toString()}</div>
        </>
      )}
      <br />
      <i>
        This project was bootstrapped with{" "}
        <a href="https://github.com/facebook/create-react-app">
          Create React App
        </a>
        .
      </i>
    </main>
  );
}

export default App;

// templates/demo/web3js-angular-dapp-demo/src/app/app.component.ts
import { Component, Pipe, type PipeTransform, type Signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Web3Service } from './web3/web3.service';
import { type providers } from 'web3';

@Pipe({
  name: 'removeProvider',
  standalone: true,
})
export class RemoveProviderPipe implements PipeTransform {
  transform(
    value: providers.EIP6963ProviderDetail[],
    target: providers.EIP6963ProviderDetail | undefined,
  ): providers.EIP6963ProviderDetail[] {
    if (target === undefined) {
      return value;
    }

    return value.filter(
      (provider: providers.EIP6963ProviderDetail) =>
        provider.info.uuid !== target.info.uuid,
    );
  }
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RemoveProviderPipe, RouterOutlet],
  templateUrl: './app.component.html',
})
export class AppComponent {
  providers: Signal<providers.EIP6963ProviderDetail[]>;
  currentProvider: Signal<providers.EIP6963ProviderDetail | undefined>;
  chainId: Signal<bigint | undefined>;
  constructor(protected web3Service: Web3Service) {
    this.providers = web3Service.providers;
    this.currentProvider = web3Service.currentProvider;
    this.chainId = web3Service.chainId;
  }
}

<main>
  <h1>Web3.js + Angular Minimal dApp Template</h1>
  <div>
    This is a sample project that demonstrates using
    <a href="https://web3js.org/">Web3.js</a> with the
    <a href="https://angular.dev/">Angular</a> front-end framework.
    <ul>
      <li><a href="https://docs.web3js.org/">Web3.js Docs</a></li>
      <li><a href="https://angular.dev/overview">Angular Docs</a></li>
    </ul>
    Learn more about this project and its design by referring to the
    <a
      href="https://github.com/web3/create-web3js-dapp/blob/main/templates/min/web3js-angular-dapp-min/README.md"
      >GitHub README</a
    >.
  </div>
  @if (providers().length === 0) {
    <h2>Install a Wallet</h2>
    <div>Install a wallet browser extension:</div>
    <ul>
      <li><a href="https://www.enkrypt.com/download.html">Enkrypt</a></li>
      <li><a href="https://www.exodus.com/download/">Exodus</a></li>
      <li><a href="https://metamask.io/download/">MetaMask</a></li>
      <li><a href="https://trustwallet.com/download">Trust Wallet</a></li>
    </ul>
  } @else {
    @if (currentProvider() === undefined) {
      <h2>Select a Provider</h2>
      @for (provider of providers(); track provider.info.uuid) {
        <div>
          <button
            (click)="web3Service.setProvider(provider)"
            style="display: inline-flex; align-items: center"
          >
            <img
              src="{{ provider.info.icon }}"
              alt="{{ provider.info.name }}"
              width="35"
            />
            <span> {{ provider.info.name }}</span>
          </button>
        </div>
      }
    } @else {
      @if (providers().length > 1) {
        <h2>Switch Provider</h2>
        @for (
          provider of providers() | removeProvider: currentProvider();
          track provider.info.uuid
        ) {
          <div>
            <button
              (click)="web3Service.setProvider(provider)"
              style="display: inline-flex; align-items: center"
            >
              <img
                src="{{ provider.info.icon }}"
                alt="{{ provider.info.name }}"
                width="35"
              />
              <span> {{ provider.info.name }}</span>
            </button>
          </div>
        }
      }
      <h2>Network Details</h2>
      <div>Chain ID: {{ chainId() }}</div>
    }
  }
  <br />
  <i
    >This project was generated with
    <a href="https://github.com/angular/angular-cli">Angular CLI</a> version
    18.2.3.</i
  >
</main>

<router-outlet />
